# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_hk_struct')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_hk_struct')
    _hk_struct = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_hk_struct', [dirname(__file__)])
        except ImportError:
            import _hk_struct
            return _hk_struct
        try:
            _mod = imp.load_module('_hk_struct', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _hk_struct = swig_import_helper()
    del swig_import_helper
else:
    import _hk_struct
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

SERIALNO_LEN = _hk_struct.SERIALNO_LEN
class NET_DVR_DEVICEINFO_V30(_object):
    """Proxy of C++ NET_DVR_DEVICEINFO_V30 class."""

    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, NET_DVR_DEVICEINFO_V30, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, NET_DVR_DEVICEINFO_V30, name)
    __repr__ = _swig_repr
    __swig_setmethods__["sSerialNumber"] = _hk_struct.NET_DVR_DEVICEINFO_V30_sSerialNumber_set
    __swig_getmethods__["sSerialNumber"] = _hk_struct.NET_DVR_DEVICEINFO_V30_sSerialNumber_get
    if _newclass:
        sSerialNumber = _swig_property(_hk_struct.NET_DVR_DEVICEINFO_V30_sSerialNumber_get, _hk_struct.NET_DVR_DEVICEINFO_V30_sSerialNumber_set)
    __swig_setmethods__["byAlarmInPortNum"] = _hk_struct.NET_DVR_DEVICEINFO_V30_byAlarmInPortNum_set
    __swig_getmethods__["byAlarmInPortNum"] = _hk_struct.NET_DVR_DEVICEINFO_V30_byAlarmInPortNum_get
    if _newclass:
        byAlarmInPortNum = _swig_property(_hk_struct.NET_DVR_DEVICEINFO_V30_byAlarmInPortNum_get, _hk_struct.NET_DVR_DEVICEINFO_V30_byAlarmInPortNum_set)
    __swig_setmethods__["byAlarmOutPortNum"] = _hk_struct.NET_DVR_DEVICEINFO_V30_byAlarmOutPortNum_set
    __swig_getmethods__["byAlarmOutPortNum"] = _hk_struct.NET_DVR_DEVICEINFO_V30_byAlarmOutPortNum_get
    if _newclass:
        byAlarmOutPortNum = _swig_property(_hk_struct.NET_DVR_DEVICEINFO_V30_byAlarmOutPortNum_get, _hk_struct.NET_DVR_DEVICEINFO_V30_byAlarmOutPortNum_set)
    __swig_setmethods__["byDiskNum"] = _hk_struct.NET_DVR_DEVICEINFO_V30_byDiskNum_set
    __swig_getmethods__["byDiskNum"] = _hk_struct.NET_DVR_DEVICEINFO_V30_byDiskNum_get
    if _newclass:
        byDiskNum = _swig_property(_hk_struct.NET_DVR_DEVICEINFO_V30_byDiskNum_get, _hk_struct.NET_DVR_DEVICEINFO_V30_byDiskNum_set)
    __swig_setmethods__["byDVRType"] = _hk_struct.NET_DVR_DEVICEINFO_V30_byDVRType_set
    __swig_getmethods__["byDVRType"] = _hk_struct.NET_DVR_DEVICEINFO_V30_byDVRType_get
    if _newclass:
        byDVRType = _swig_property(_hk_struct.NET_DVR_DEVICEINFO_V30_byDVRType_get, _hk_struct.NET_DVR_DEVICEINFO_V30_byDVRType_set)
    __swig_setmethods__["byChanNum"] = _hk_struct.NET_DVR_DEVICEINFO_V30_byChanNum_set
    __swig_getmethods__["byChanNum"] = _hk_struct.NET_DVR_DEVICEINFO_V30_byChanNum_get
    if _newclass:
        byChanNum = _swig_property(_hk_struct.NET_DVR_DEVICEINFO_V30_byChanNum_get, _hk_struct.NET_DVR_DEVICEINFO_V30_byChanNum_set)
    __swig_setmethods__["byStartChan"] = _hk_struct.NET_DVR_DEVICEINFO_V30_byStartChan_set
    __swig_getmethods__["byStartChan"] = _hk_struct.NET_DVR_DEVICEINFO_V30_byStartChan_get
    if _newclass:
        byStartChan = _swig_property(_hk_struct.NET_DVR_DEVICEINFO_V30_byStartChan_get, _hk_struct.NET_DVR_DEVICEINFO_V30_byStartChan_set)
    __swig_setmethods__["byAudioChanNum"] = _hk_struct.NET_DVR_DEVICEINFO_V30_byAudioChanNum_set
    __swig_getmethods__["byAudioChanNum"] = _hk_struct.NET_DVR_DEVICEINFO_V30_byAudioChanNum_get
    if _newclass:
        byAudioChanNum = _swig_property(_hk_struct.NET_DVR_DEVICEINFO_V30_byAudioChanNum_get, _hk_struct.NET_DVR_DEVICEINFO_V30_byAudioChanNum_set)
    __swig_setmethods__["byIPChanNum"] = _hk_struct.NET_DVR_DEVICEINFO_V30_byIPChanNum_set
    __swig_getmethods__["byIPChanNum"] = _hk_struct.NET_DVR_DEVICEINFO_V30_byIPChanNum_get
    if _newclass:
        byIPChanNum = _swig_property(_hk_struct.NET_DVR_DEVICEINFO_V30_byIPChanNum_get, _hk_struct.NET_DVR_DEVICEINFO_V30_byIPChanNum_set)
    __swig_setmethods__["byZeroChanNum"] = _hk_struct.NET_DVR_DEVICEINFO_V30_byZeroChanNum_set
    __swig_getmethods__["byZeroChanNum"] = _hk_struct.NET_DVR_DEVICEINFO_V30_byZeroChanNum_get
    if _newclass:
        byZeroChanNum = _swig_property(_hk_struct.NET_DVR_DEVICEINFO_V30_byZeroChanNum_get, _hk_struct.NET_DVR_DEVICEINFO_V30_byZeroChanNum_set)
    __swig_setmethods__["byMainProto"] = _hk_struct.NET_DVR_DEVICEINFO_V30_byMainProto_set
    __swig_getmethods__["byMainProto"] = _hk_struct.NET_DVR_DEVICEINFO_V30_byMainProto_get
    if _newclass:
        byMainProto = _swig_property(_hk_struct.NET_DVR_DEVICEINFO_V30_byMainProto_get, _hk_struct.NET_DVR_DEVICEINFO_V30_byMainProto_set)
    __swig_setmethods__["bySubProto"] = _hk_struct.NET_DVR_DEVICEINFO_V30_bySubProto_set
    __swig_getmethods__["bySubProto"] = _hk_struct.NET_DVR_DEVICEINFO_V30_bySubProto_get
    if _newclass:
        bySubProto = _swig_property(_hk_struct.NET_DVR_DEVICEINFO_V30_bySubProto_get, _hk_struct.NET_DVR_DEVICEINFO_V30_bySubProto_set)
    __swig_setmethods__["bySupport"] = _hk_struct.NET_DVR_DEVICEINFO_V30_bySupport_set
    __swig_getmethods__["bySupport"] = _hk_struct.NET_DVR_DEVICEINFO_V30_bySupport_get
    if _newclass:
        bySupport = _swig_property(_hk_struct.NET_DVR_DEVICEINFO_V30_bySupport_get, _hk_struct.NET_DVR_DEVICEINFO_V30_bySupport_set)
    __swig_setmethods__["bySupport1"] = _hk_struct.NET_DVR_DEVICEINFO_V30_bySupport1_set
    __swig_getmethods__["bySupport1"] = _hk_struct.NET_DVR_DEVICEINFO_V30_bySupport1_get
    if _newclass:
        bySupport1 = _swig_property(_hk_struct.NET_DVR_DEVICEINFO_V30_bySupport1_get, _hk_struct.NET_DVR_DEVICEINFO_V30_bySupport1_set)
    __swig_setmethods__["bySupport2"] = _hk_struct.NET_DVR_DEVICEINFO_V30_bySupport2_set
    __swig_getmethods__["bySupport2"] = _hk_struct.NET_DVR_DEVICEINFO_V30_bySupport2_get
    if _newclass:
        bySupport2 = _swig_property(_hk_struct.NET_DVR_DEVICEINFO_V30_bySupport2_get, _hk_struct.NET_DVR_DEVICEINFO_V30_bySupport2_set)
    __swig_setmethods__["wDevType"] = _hk_struct.NET_DVR_DEVICEINFO_V30_wDevType_set
    __swig_getmethods__["wDevType"] = _hk_struct.NET_DVR_DEVICEINFO_V30_wDevType_get
    if _newclass:
        wDevType = _swig_property(_hk_struct.NET_DVR_DEVICEINFO_V30_wDevType_get, _hk_struct.NET_DVR_DEVICEINFO_V30_wDevType_set)
    __swig_setmethods__["bySupport3"] = _hk_struct.NET_DVR_DEVICEINFO_V30_bySupport3_set
    __swig_getmethods__["bySupport3"] = _hk_struct.NET_DVR_DEVICEINFO_V30_bySupport3_get
    if _newclass:
        bySupport3 = _swig_property(_hk_struct.NET_DVR_DEVICEINFO_V30_bySupport3_get, _hk_struct.NET_DVR_DEVICEINFO_V30_bySupport3_set)
    __swig_setmethods__["byMultiStreamProto"] = _hk_struct.NET_DVR_DEVICEINFO_V30_byMultiStreamProto_set
    __swig_getmethods__["byMultiStreamProto"] = _hk_struct.NET_DVR_DEVICEINFO_V30_byMultiStreamProto_get
    if _newclass:
        byMultiStreamProto = _swig_property(_hk_struct.NET_DVR_DEVICEINFO_V30_byMultiStreamProto_get, _hk_struct.NET_DVR_DEVICEINFO_V30_byMultiStreamProto_set)
    __swig_setmethods__["byStartDChan"] = _hk_struct.NET_DVR_DEVICEINFO_V30_byStartDChan_set
    __swig_getmethods__["byStartDChan"] = _hk_struct.NET_DVR_DEVICEINFO_V30_byStartDChan_get
    if _newclass:
        byStartDChan = _swig_property(_hk_struct.NET_DVR_DEVICEINFO_V30_byStartDChan_get, _hk_struct.NET_DVR_DEVICEINFO_V30_byStartDChan_set)
    __swig_setmethods__["byStartDTalkChan"] = _hk_struct.NET_DVR_DEVICEINFO_V30_byStartDTalkChan_set
    __swig_getmethods__["byStartDTalkChan"] = _hk_struct.NET_DVR_DEVICEINFO_V30_byStartDTalkChan_get
    if _newclass:
        byStartDTalkChan = _swig_property(_hk_struct.NET_DVR_DEVICEINFO_V30_byStartDTalkChan_get, _hk_struct.NET_DVR_DEVICEINFO_V30_byStartDTalkChan_set)
    __swig_setmethods__["byHighDChanNum"] = _hk_struct.NET_DVR_DEVICEINFO_V30_byHighDChanNum_set
    __swig_getmethods__["byHighDChanNum"] = _hk_struct.NET_DVR_DEVICEINFO_V30_byHighDChanNum_get
    if _newclass:
        byHighDChanNum = _swig_property(_hk_struct.NET_DVR_DEVICEINFO_V30_byHighDChanNum_get, _hk_struct.NET_DVR_DEVICEINFO_V30_byHighDChanNum_set)
    __swig_setmethods__["bySupport4"] = _hk_struct.NET_DVR_DEVICEINFO_V30_bySupport4_set
    __swig_getmethods__["bySupport4"] = _hk_struct.NET_DVR_DEVICEINFO_V30_bySupport4_get
    if _newclass:
        bySupport4 = _swig_property(_hk_struct.NET_DVR_DEVICEINFO_V30_bySupport4_get, _hk_struct.NET_DVR_DEVICEINFO_V30_bySupport4_set)
    __swig_setmethods__["byLanguageType"] = _hk_struct.NET_DVR_DEVICEINFO_V30_byLanguageType_set
    __swig_getmethods__["byLanguageType"] = _hk_struct.NET_DVR_DEVICEINFO_V30_byLanguageType_get
    if _newclass:
        byLanguageType = _swig_property(_hk_struct.NET_DVR_DEVICEINFO_V30_byLanguageType_get, _hk_struct.NET_DVR_DEVICEINFO_V30_byLanguageType_set)
    __swig_setmethods__["byVoiceInChanNum"] = _hk_struct.NET_DVR_DEVICEINFO_V30_byVoiceInChanNum_set
    __swig_getmethods__["byVoiceInChanNum"] = _hk_struct.NET_DVR_DEVICEINFO_V30_byVoiceInChanNum_get
    if _newclass:
        byVoiceInChanNum = _swig_property(_hk_struct.NET_DVR_DEVICEINFO_V30_byVoiceInChanNum_get, _hk_struct.NET_DVR_DEVICEINFO_V30_byVoiceInChanNum_set)
    __swig_setmethods__["byStartVoiceInChanNo"] = _hk_struct.NET_DVR_DEVICEINFO_V30_byStartVoiceInChanNo_set
    __swig_getmethods__["byStartVoiceInChanNo"] = _hk_struct.NET_DVR_DEVICEINFO_V30_byStartVoiceInChanNo_get
    if _newclass:
        byStartVoiceInChanNo = _swig_property(_hk_struct.NET_DVR_DEVICEINFO_V30_byStartVoiceInChanNo_get, _hk_struct.NET_DVR_DEVICEINFO_V30_byStartVoiceInChanNo_set)
    __swig_setmethods__["bySupport5"] = _hk_struct.NET_DVR_DEVICEINFO_V30_bySupport5_set
    __swig_getmethods__["bySupport5"] = _hk_struct.NET_DVR_DEVICEINFO_V30_bySupport5_get
    if _newclass:
        bySupport5 = _swig_property(_hk_struct.NET_DVR_DEVICEINFO_V30_bySupport5_get, _hk_struct.NET_DVR_DEVICEINFO_V30_bySupport5_set)
    __swig_setmethods__["bySupport6"] = _hk_struct.NET_DVR_DEVICEINFO_V30_bySupport6_set
    __swig_getmethods__["bySupport6"] = _hk_struct.NET_DVR_DEVICEINFO_V30_bySupport6_get
    if _newclass:
        bySupport6 = _swig_property(_hk_struct.NET_DVR_DEVICEINFO_V30_bySupport6_get, _hk_struct.NET_DVR_DEVICEINFO_V30_bySupport6_set)
    __swig_setmethods__["byMirrorChanNum"] = _hk_struct.NET_DVR_DEVICEINFO_V30_byMirrorChanNum_set
    __swig_getmethods__["byMirrorChanNum"] = _hk_struct.NET_DVR_DEVICEINFO_V30_byMirrorChanNum_get
    if _newclass:
        byMirrorChanNum = _swig_property(_hk_struct.NET_DVR_DEVICEINFO_V30_byMirrorChanNum_get, _hk_struct.NET_DVR_DEVICEINFO_V30_byMirrorChanNum_set)
    __swig_setmethods__["wStartMirrorChanNo"] = _hk_struct.NET_DVR_DEVICEINFO_V30_wStartMirrorChanNo_set
    __swig_getmethods__["wStartMirrorChanNo"] = _hk_struct.NET_DVR_DEVICEINFO_V30_wStartMirrorChanNo_get
    if _newclass:
        wStartMirrorChanNo = _swig_property(_hk_struct.NET_DVR_DEVICEINFO_V30_wStartMirrorChanNo_get, _hk_struct.NET_DVR_DEVICEINFO_V30_wStartMirrorChanNo_set)
    __swig_setmethods__["bySupport7"] = _hk_struct.NET_DVR_DEVICEINFO_V30_bySupport7_set
    __swig_getmethods__["bySupport7"] = _hk_struct.NET_DVR_DEVICEINFO_V30_bySupport7_get
    if _newclass:
        bySupport7 = _swig_property(_hk_struct.NET_DVR_DEVICEINFO_V30_bySupport7_get, _hk_struct.NET_DVR_DEVICEINFO_V30_bySupport7_set)
    __swig_setmethods__["byRes2"] = _hk_struct.NET_DVR_DEVICEINFO_V30_byRes2_set
    __swig_getmethods__["byRes2"] = _hk_struct.NET_DVR_DEVICEINFO_V30_byRes2_get
    if _newclass:
        byRes2 = _swig_property(_hk_struct.NET_DVR_DEVICEINFO_V30_byRes2_get, _hk_struct.NET_DVR_DEVICEINFO_V30_byRes2_set)

    def __init__(self):
        """__init__(self) -> NET_DVR_DEVICEINFO_V30"""
        this = _hk_struct.new_NET_DVR_DEVICEINFO_V30()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _hk_struct.delete_NET_DVR_DEVICEINFO_V30
    __del__ = lambda self: None
NET_DVR_DEVICEINFO_V30_swigregister = _hk_struct.NET_DVR_DEVICEINFO_V30_swigregister
NET_DVR_DEVICEINFO_V30_swigregister(NET_DVR_DEVICEINFO_V30)

# This file is compatible with both classic and new-style classes.


