#!/usr/bin/env python3

from distutils.core import setup, Extension
import os
pwd = os.getcwd()
module1 = Extension('_pyhk',
                    sources=['pyhk/py_hk.i'],
                    swig_opts=['-c++', '-py3'],
                    include_dirs=['pyhk/include'],
                    # runtime_library_dirs=['pyhk/lib'],
                    libraries=[
                        'pyhk\lib\libanalyzedata.so',
                        'pyhk\lib\libAudioRender.so',
                        'pyhk\lib\libcrypto.so',
                        'pyhk\lib\libcrypto.so.1.0.0',
                        'pyhk\lib\libHCAlarm.so',
                        'pyhk\lib\libHCCore.so',
                        'pyhk\lib\libHCCoreDevCfg.so',
                        'pyhk\lib\libHCDisplay.so',
                        'pyhk\lib\libHCGeneralCfgMgr.so',
                        'pyhk\lib\libHCIndustry.so',
                        'pyhk\lib\libhcnetsdk.so',
                        'pyhk\lib\libHCPlayBack.so',
                        'pyhk\lib\libHCPreview.so',
                        'pyhk\lib\libHCVoiceTalk.so',
                        'pyhk\lib\libhpr.so',
                        'pyhk\lib\libiconv2.so',
                        'pyhk\lib\libNPQos.so',
                        'pyhk\lib\libopenal.so.1',
                        'pyhk\lib\libPlayCtrl.so',
                        'pyhk\lib\libssl.so',
                        'pyhk\lib\libStreamTransClient.so',
                        'pyhk\lib\libSuperRender.so',
                        'pyhk\lib\libSystemTransform.so',
                        'pyhk\lib\libz.so',
                        'pyhk\lib\HCNetSDKCom\libanalyzedata.so',
                        'pyhk\lib\HCNetSDKCom\libHCAlarm.so',
                        'pyhk\lib\HCNetSDKCom\libHCCoreDevCfg.so',
                        'pyhk\lib\HCNetSDKCom\libHCDisplay.so',
                        'pyhk\lib\HCNetSDKCom\libHCGeneralCfgMgr.so',
                        'pyhk\lib\HCNetSDKCom\libHCIndustry.so',
                        'pyhk\lib\HCNetSDKCom\libHCPlayBack.so',
                        'pyhk\lib\HCNetSDKCom\libHCPreview.so',
                        'pyhk\lib\HCNetSDKCom\libHCVoiceTalk.so',
                        'pyhk\lib\HCNetSDKCom\libiconv2.so',
                        'pyhk\lib\HCNetSDKCom\libStreamTransClient.so',
                        'pyhk\lib\HCNetSDKCom\libSystemTransform.so',
                    ],
                    # extra_compile_args=['-std=c++11', '-O2', '-fPIC']
                    )
setup(name='pyhk',
      version='0.1',
      author="SWIG Docs",
      description="""Simple swig example from docs""",
      ext_modules=[module1],
      #   py_modules=["pyhk.py"],
      )
