# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_pyhk')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_pyhk')
    _pyhk = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_pyhk', [dirname(__file__)])
        except ImportError:
            import _pyhk
            return _pyhk
        try:
            _mod = imp.load_module('_pyhk', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _pyhk = swig_import_helper()
    del swig_import_helper
else:
    import _pyhk
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

try:
    import weakref
    weakref_proxy = weakref.proxy
except __builtin__.Exception:
    weakref_proxy = lambda x: x


class NET_DVR_SETUPALARM_PARAM(_object):
    """Proxy of C++ tagNET_DVR_SETUPALARM_PARAM class."""

    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, NET_DVR_SETUPALARM_PARAM, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, NET_DVR_SETUPALARM_PARAM, name)
    __repr__ = _swig_repr
    __swig_setmethods__["dwSize"] = _pyhk.NET_DVR_SETUPALARM_PARAM_dwSize_set
    __swig_getmethods__["dwSize"] = _pyhk.NET_DVR_SETUPALARM_PARAM_dwSize_get
    if _newclass:
        dwSize = _swig_property(_pyhk.NET_DVR_SETUPALARM_PARAM_dwSize_get, _pyhk.NET_DVR_SETUPALARM_PARAM_dwSize_set)
    __swig_setmethods__["byLevel"] = _pyhk.NET_DVR_SETUPALARM_PARAM_byLevel_set
    __swig_getmethods__["byLevel"] = _pyhk.NET_DVR_SETUPALARM_PARAM_byLevel_get
    if _newclass:
        byLevel = _swig_property(_pyhk.NET_DVR_SETUPALARM_PARAM_byLevel_get, _pyhk.NET_DVR_SETUPALARM_PARAM_byLevel_set)
    __swig_setmethods__["byAlarmInfoType"] = _pyhk.NET_DVR_SETUPALARM_PARAM_byAlarmInfoType_set
    __swig_getmethods__["byAlarmInfoType"] = _pyhk.NET_DVR_SETUPALARM_PARAM_byAlarmInfoType_get
    if _newclass:
        byAlarmInfoType = _swig_property(_pyhk.NET_DVR_SETUPALARM_PARAM_byAlarmInfoType_get, _pyhk.NET_DVR_SETUPALARM_PARAM_byAlarmInfoType_set)
    __swig_setmethods__["byRetAlarmTypeV40"] = _pyhk.NET_DVR_SETUPALARM_PARAM_byRetAlarmTypeV40_set
    __swig_getmethods__["byRetAlarmTypeV40"] = _pyhk.NET_DVR_SETUPALARM_PARAM_byRetAlarmTypeV40_get
    if _newclass:
        byRetAlarmTypeV40 = _swig_property(_pyhk.NET_DVR_SETUPALARM_PARAM_byRetAlarmTypeV40_get, _pyhk.NET_DVR_SETUPALARM_PARAM_byRetAlarmTypeV40_set)
    __swig_setmethods__["byRetDevInfoVersion"] = _pyhk.NET_DVR_SETUPALARM_PARAM_byRetDevInfoVersion_set
    __swig_getmethods__["byRetDevInfoVersion"] = _pyhk.NET_DVR_SETUPALARM_PARAM_byRetDevInfoVersion_get
    if _newclass:
        byRetDevInfoVersion = _swig_property(_pyhk.NET_DVR_SETUPALARM_PARAM_byRetDevInfoVersion_get, _pyhk.NET_DVR_SETUPALARM_PARAM_byRetDevInfoVersion_set)
    __swig_setmethods__["byRetVQDAlarmType"] = _pyhk.NET_DVR_SETUPALARM_PARAM_byRetVQDAlarmType_set
    __swig_getmethods__["byRetVQDAlarmType"] = _pyhk.NET_DVR_SETUPALARM_PARAM_byRetVQDAlarmType_get
    if _newclass:
        byRetVQDAlarmType = _swig_property(_pyhk.NET_DVR_SETUPALARM_PARAM_byRetVQDAlarmType_get, _pyhk.NET_DVR_SETUPALARM_PARAM_byRetVQDAlarmType_set)
    __swig_setmethods__["byFaceAlarmDetection"] = _pyhk.NET_DVR_SETUPALARM_PARAM_byFaceAlarmDetection_set
    __swig_getmethods__["byFaceAlarmDetection"] = _pyhk.NET_DVR_SETUPALARM_PARAM_byFaceAlarmDetection_get
    if _newclass:
        byFaceAlarmDetection = _swig_property(_pyhk.NET_DVR_SETUPALARM_PARAM_byFaceAlarmDetection_get, _pyhk.NET_DVR_SETUPALARM_PARAM_byFaceAlarmDetection_set)
    __swig_setmethods__["bySupport"] = _pyhk.NET_DVR_SETUPALARM_PARAM_bySupport_set
    __swig_getmethods__["bySupport"] = _pyhk.NET_DVR_SETUPALARM_PARAM_bySupport_get
    if _newclass:
        bySupport = _swig_property(_pyhk.NET_DVR_SETUPALARM_PARAM_bySupport_get, _pyhk.NET_DVR_SETUPALARM_PARAM_bySupport_set)
    __swig_setmethods__["byBrokenNetHttp"] = _pyhk.NET_DVR_SETUPALARM_PARAM_byBrokenNetHttp_set
    __swig_getmethods__["byBrokenNetHttp"] = _pyhk.NET_DVR_SETUPALARM_PARAM_byBrokenNetHttp_get
    if _newclass:
        byBrokenNetHttp = _swig_property(_pyhk.NET_DVR_SETUPALARM_PARAM_byBrokenNetHttp_get, _pyhk.NET_DVR_SETUPALARM_PARAM_byBrokenNetHttp_set)
    __swig_setmethods__["wTaskNo"] = _pyhk.NET_DVR_SETUPALARM_PARAM_wTaskNo_set
    __swig_getmethods__["wTaskNo"] = _pyhk.NET_DVR_SETUPALARM_PARAM_wTaskNo_get
    if _newclass:
        wTaskNo = _swig_property(_pyhk.NET_DVR_SETUPALARM_PARAM_wTaskNo_get, _pyhk.NET_DVR_SETUPALARM_PARAM_wTaskNo_set)
    __swig_setmethods__["byDeployType"] = _pyhk.NET_DVR_SETUPALARM_PARAM_byDeployType_set
    __swig_getmethods__["byDeployType"] = _pyhk.NET_DVR_SETUPALARM_PARAM_byDeployType_get
    if _newclass:
        byDeployType = _swig_property(_pyhk.NET_DVR_SETUPALARM_PARAM_byDeployType_get, _pyhk.NET_DVR_SETUPALARM_PARAM_byDeployType_set)
    __swig_setmethods__["byRes1"] = _pyhk.NET_DVR_SETUPALARM_PARAM_byRes1_set
    __swig_getmethods__["byRes1"] = _pyhk.NET_DVR_SETUPALARM_PARAM_byRes1_get
    if _newclass:
        byRes1 = _swig_property(_pyhk.NET_DVR_SETUPALARM_PARAM_byRes1_get, _pyhk.NET_DVR_SETUPALARM_PARAM_byRes1_set)
    __swig_setmethods__["byAlarmTypeURL"] = _pyhk.NET_DVR_SETUPALARM_PARAM_byAlarmTypeURL_set
    __swig_getmethods__["byAlarmTypeURL"] = _pyhk.NET_DVR_SETUPALARM_PARAM_byAlarmTypeURL_get
    if _newclass:
        byAlarmTypeURL = _swig_property(_pyhk.NET_DVR_SETUPALARM_PARAM_byAlarmTypeURL_get, _pyhk.NET_DVR_SETUPALARM_PARAM_byAlarmTypeURL_set)
    __swig_setmethods__["byCustomCtrl"] = _pyhk.NET_DVR_SETUPALARM_PARAM_byCustomCtrl_set
    __swig_getmethods__["byCustomCtrl"] = _pyhk.NET_DVR_SETUPALARM_PARAM_byCustomCtrl_get
    if _newclass:
        byCustomCtrl = _swig_property(_pyhk.NET_DVR_SETUPALARM_PARAM_byCustomCtrl_get, _pyhk.NET_DVR_SETUPALARM_PARAM_byCustomCtrl_set)

    def __init__(self):
        """__init__(self) -> NET_DVR_SETUPALARM_PARAM"""
        this = _pyhk.new_NET_DVR_SETUPALARM_PARAM()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _pyhk.delete_NET_DVR_SETUPALARM_PARAM
    __del__ = lambda self: None
NET_DVR_SETUPALARM_PARAM_swigregister = _pyhk.NET_DVR_SETUPALARM_PARAM_swigregister
NET_DVR_SETUPALARM_PARAM_swigregister(NET_DVR_SETUPALARM_PARAM)

class NET_DVR_ALARMER(_object):
    """Proxy of C++ NET_DVR_ALARMER class."""

    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, NET_DVR_ALARMER, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, NET_DVR_ALARMER, name)
    __repr__ = _swig_repr
    __swig_setmethods__["byUserIDValid"] = _pyhk.NET_DVR_ALARMER_byUserIDValid_set
    __swig_getmethods__["byUserIDValid"] = _pyhk.NET_DVR_ALARMER_byUserIDValid_get
    if _newclass:
        byUserIDValid = _swig_property(_pyhk.NET_DVR_ALARMER_byUserIDValid_get, _pyhk.NET_DVR_ALARMER_byUserIDValid_set)
    __swig_setmethods__["bySerialValid"] = _pyhk.NET_DVR_ALARMER_bySerialValid_set
    __swig_getmethods__["bySerialValid"] = _pyhk.NET_DVR_ALARMER_bySerialValid_get
    if _newclass:
        bySerialValid = _swig_property(_pyhk.NET_DVR_ALARMER_bySerialValid_get, _pyhk.NET_DVR_ALARMER_bySerialValid_set)
    __swig_setmethods__["byVersionValid"] = _pyhk.NET_DVR_ALARMER_byVersionValid_set
    __swig_getmethods__["byVersionValid"] = _pyhk.NET_DVR_ALARMER_byVersionValid_get
    if _newclass:
        byVersionValid = _swig_property(_pyhk.NET_DVR_ALARMER_byVersionValid_get, _pyhk.NET_DVR_ALARMER_byVersionValid_set)
    __swig_setmethods__["byDeviceNameValid"] = _pyhk.NET_DVR_ALARMER_byDeviceNameValid_set
    __swig_getmethods__["byDeviceNameValid"] = _pyhk.NET_DVR_ALARMER_byDeviceNameValid_get
    if _newclass:
        byDeviceNameValid = _swig_property(_pyhk.NET_DVR_ALARMER_byDeviceNameValid_get, _pyhk.NET_DVR_ALARMER_byDeviceNameValid_set)
    __swig_setmethods__["byMacAddrValid"] = _pyhk.NET_DVR_ALARMER_byMacAddrValid_set
    __swig_getmethods__["byMacAddrValid"] = _pyhk.NET_DVR_ALARMER_byMacAddrValid_get
    if _newclass:
        byMacAddrValid = _swig_property(_pyhk.NET_DVR_ALARMER_byMacAddrValid_get, _pyhk.NET_DVR_ALARMER_byMacAddrValid_set)
    __swig_setmethods__["byLinkPortValid"] = _pyhk.NET_DVR_ALARMER_byLinkPortValid_set
    __swig_getmethods__["byLinkPortValid"] = _pyhk.NET_DVR_ALARMER_byLinkPortValid_get
    if _newclass:
        byLinkPortValid = _swig_property(_pyhk.NET_DVR_ALARMER_byLinkPortValid_get, _pyhk.NET_DVR_ALARMER_byLinkPortValid_set)
    __swig_setmethods__["byDeviceIPValid"] = _pyhk.NET_DVR_ALARMER_byDeviceIPValid_set
    __swig_getmethods__["byDeviceIPValid"] = _pyhk.NET_DVR_ALARMER_byDeviceIPValid_get
    if _newclass:
        byDeviceIPValid = _swig_property(_pyhk.NET_DVR_ALARMER_byDeviceIPValid_get, _pyhk.NET_DVR_ALARMER_byDeviceIPValid_set)
    __swig_setmethods__["bySocketIPValid"] = _pyhk.NET_DVR_ALARMER_bySocketIPValid_set
    __swig_getmethods__["bySocketIPValid"] = _pyhk.NET_DVR_ALARMER_bySocketIPValid_get
    if _newclass:
        bySocketIPValid = _swig_property(_pyhk.NET_DVR_ALARMER_bySocketIPValid_get, _pyhk.NET_DVR_ALARMER_bySocketIPValid_set)
    __swig_setmethods__["lUserID"] = _pyhk.NET_DVR_ALARMER_lUserID_set
    __swig_getmethods__["lUserID"] = _pyhk.NET_DVR_ALARMER_lUserID_get
    if _newclass:
        lUserID = _swig_property(_pyhk.NET_DVR_ALARMER_lUserID_get, _pyhk.NET_DVR_ALARMER_lUserID_set)
    __swig_setmethods__["sSerialNumber"] = _pyhk.NET_DVR_ALARMER_sSerialNumber_set
    __swig_getmethods__["sSerialNumber"] = _pyhk.NET_DVR_ALARMER_sSerialNumber_get
    if _newclass:
        sSerialNumber = _swig_property(_pyhk.NET_DVR_ALARMER_sSerialNumber_get, _pyhk.NET_DVR_ALARMER_sSerialNumber_set)
    __swig_setmethods__["dwDeviceVersion"] = _pyhk.NET_DVR_ALARMER_dwDeviceVersion_set
    __swig_getmethods__["dwDeviceVersion"] = _pyhk.NET_DVR_ALARMER_dwDeviceVersion_get
    if _newclass:
        dwDeviceVersion = _swig_property(_pyhk.NET_DVR_ALARMER_dwDeviceVersion_get, _pyhk.NET_DVR_ALARMER_dwDeviceVersion_set)
    __swig_setmethods__["sDeviceName"] = _pyhk.NET_DVR_ALARMER_sDeviceName_set
    __swig_getmethods__["sDeviceName"] = _pyhk.NET_DVR_ALARMER_sDeviceName_get
    if _newclass:
        sDeviceName = _swig_property(_pyhk.NET_DVR_ALARMER_sDeviceName_get, _pyhk.NET_DVR_ALARMER_sDeviceName_set)
    __swig_setmethods__["byMacAddr"] = _pyhk.NET_DVR_ALARMER_byMacAddr_set
    __swig_getmethods__["byMacAddr"] = _pyhk.NET_DVR_ALARMER_byMacAddr_get
    if _newclass:
        byMacAddr = _swig_property(_pyhk.NET_DVR_ALARMER_byMacAddr_get, _pyhk.NET_DVR_ALARMER_byMacAddr_set)
    __swig_setmethods__["wLinkPort"] = _pyhk.NET_DVR_ALARMER_wLinkPort_set
    __swig_getmethods__["wLinkPort"] = _pyhk.NET_DVR_ALARMER_wLinkPort_get
    if _newclass:
        wLinkPort = _swig_property(_pyhk.NET_DVR_ALARMER_wLinkPort_get, _pyhk.NET_DVR_ALARMER_wLinkPort_set)
    __swig_setmethods__["sDeviceIP"] = _pyhk.NET_DVR_ALARMER_sDeviceIP_set
    __swig_getmethods__["sDeviceIP"] = _pyhk.NET_DVR_ALARMER_sDeviceIP_get
    if _newclass:
        sDeviceIP = _swig_property(_pyhk.NET_DVR_ALARMER_sDeviceIP_get, _pyhk.NET_DVR_ALARMER_sDeviceIP_set)
    __swig_setmethods__["sSocketIP"] = _pyhk.NET_DVR_ALARMER_sSocketIP_set
    __swig_getmethods__["sSocketIP"] = _pyhk.NET_DVR_ALARMER_sSocketIP_get
    if _newclass:
        sSocketIP = _swig_property(_pyhk.NET_DVR_ALARMER_sSocketIP_get, _pyhk.NET_DVR_ALARMER_sSocketIP_set)
    __swig_setmethods__["byIpProtocol"] = _pyhk.NET_DVR_ALARMER_byIpProtocol_set
    __swig_getmethods__["byIpProtocol"] = _pyhk.NET_DVR_ALARMER_byIpProtocol_get
    if _newclass:
        byIpProtocol = _swig_property(_pyhk.NET_DVR_ALARMER_byIpProtocol_get, _pyhk.NET_DVR_ALARMER_byIpProtocol_set)
    __swig_setmethods__["byRes1"] = _pyhk.NET_DVR_ALARMER_byRes1_set
    __swig_getmethods__["byRes1"] = _pyhk.NET_DVR_ALARMER_byRes1_get
    if _newclass:
        byRes1 = _swig_property(_pyhk.NET_DVR_ALARMER_byRes1_get, _pyhk.NET_DVR_ALARMER_byRes1_set)
    __swig_setmethods__["bJSONBroken"] = _pyhk.NET_DVR_ALARMER_bJSONBroken_set
    __swig_getmethods__["bJSONBroken"] = _pyhk.NET_DVR_ALARMER_bJSONBroken_get
    if _newclass:
        bJSONBroken = _swig_property(_pyhk.NET_DVR_ALARMER_bJSONBroken_get, _pyhk.NET_DVR_ALARMER_bJSONBroken_set)
    __swig_setmethods__["wSocketPort"] = _pyhk.NET_DVR_ALARMER_wSocketPort_set
    __swig_getmethods__["wSocketPort"] = _pyhk.NET_DVR_ALARMER_wSocketPort_get
    if _newclass:
        wSocketPort = _swig_property(_pyhk.NET_DVR_ALARMER_wSocketPort_get, _pyhk.NET_DVR_ALARMER_wSocketPort_set)
    __swig_setmethods__["byRes2"] = _pyhk.NET_DVR_ALARMER_byRes2_set
    __swig_getmethods__["byRes2"] = _pyhk.NET_DVR_ALARMER_byRes2_get
    if _newclass:
        byRes2 = _swig_property(_pyhk.NET_DVR_ALARMER_byRes2_get, _pyhk.NET_DVR_ALARMER_byRes2_set)

    def __init__(self):
        """__init__(self) -> NET_DVR_ALARMER"""
        this = _pyhk.new_NET_DVR_ALARMER()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _pyhk.delete_NET_DVR_ALARMER
    __del__ = lambda self: None
NET_DVR_ALARMER_swigregister = _pyhk.NET_DVR_ALARMER_swigregister
NET_DVR_ALARMER_swigregister(NET_DVR_ALARMER)

class MessageCallback_31Op(_object):
    """Proxy of C++ MessageCallback_31Op class."""

    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MessageCallback_31Op, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MessageCallback_31Op, name)
    __repr__ = _swig_repr

    def MessageCallback_31(self, lCommand: 'LONG', pAlarmer: 'NET_DVR_ALARMER', pAlarmInfo: 'char *', dwBufLen: 'DWORD', pUser: 'void *') -> "void":
        """
        MessageCallback_31(self, lCommand, pAlarmer, pAlarmInfo, dwBufLen, pUser)

        Parameters
        ----------
        lCommand: LONG
        pAlarmer: NET_DVR_ALARMER *
        pAlarmInfo: char *
        dwBufLen: DWORD
        pUser: void *

        """
        return _pyhk.MessageCallback_31Op_MessageCallback_31(self, lCommand, pAlarmer, pAlarmInfo, dwBufLen, pUser)

    __swig_destroy__ = _pyhk.delete_MessageCallback_31Op
    __del__ = lambda self: None

    def __init__(self):
        """
        __init__(self) -> MessageCallback_31Op

        Parameters
        ----------
        self: PyObject *

        """
        if self.__class__ == MessageCallback_31Op:
            _self = None
        else:
            _self = self
        this = _pyhk.new_MessageCallback_31Op(_self, )
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    def __disown__(self):
        self.this.disown()
        _pyhk.disown_MessageCallback_31Op(self)
        return weakref_proxy(self)
MessageCallback_31Op_swigregister = _pyhk.MessageCallback_31Op_swigregister
MessageCallback_31Op_swigregister(MessageCallback_31Op)


def close_jt() -> "void":
    """close_jt()"""
    return _pyhk.close_jt()

def start_jt(IP: 'char *', Username: 'char *', Password: 'char *', fMessageCallBack: 'MessageCallback_31Op') -> "int":
    """
    start_jt(IP, Username, Password, fMessageCallBack) -> int

    Parameters
    ----------
    IP: char *
    Username: char *
    Password: char *
    fMessageCallBack: MessageCallback_31Op *

    """
    return _pyhk.start_jt(IP, Username, Password, fMessageCallBack)
# This file is compatible with both classic and new-style classes.


