class NET_DVR_GetDVRConfig_dwCommand:
    """
        NET_DVR_GET_NFSCFG 获取 NFS（网络文件系统）参数
        NET_DVR_GET_HDCFG 获取硬盘管理参数
        NET_DVR_GET_HDCFG_V40 获取硬盘管理参数
        NET_DVR_GET_HDGROUP_CFG_V40 获取盘组管理参数
        NET_DVR_GET_NET_DISKCFG 获取网络硬盘接入参数
        NET_DVR_GET_DISK_QUOTA_CFG 获取磁盘配额信息
        NET_DVR_GET_DISK_RAID_INFO 获取磁盘 Raid 信息
        NET_DVR_GET_DRAWFRAME_DISK_QUOTA_CFG 获取抽帧通道磁盘配额
        NET_DVR_GET_ESATA_MINISAS_USAGE_CFG 获取 eSATA 和 miniSAS 用途
    """
    NET_DVR_GET_NFSCFG=230#获取 NFS（网络文件系统）参数
    NET_DVR_GET_HDCFG=1054
    NET_DVR_GET_HDCFG_V40=6122
    NET_DVR_GET_HDGROUP_CFG_V40=6192
    NET_DVR_GET_NET_DISKCFG=1038
    NET_DVR_GET_DISK_QUOTA_CFG=1278
    NET_DVR_GET_DISK_RAID_INFO=6001
    NET_DVR_GET_DRAWFRAME_DISK_QUOTA_CFG=6109
    NET_DVR_GET_ESATA_MINISAS_USAGE_CFG=6120