# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

"""本模块主要用于海康威视的接口封装"""


from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_pyhk')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_pyhk')
    _pyhk = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_pyhk', [dirname(__file__)])
        except ImportError:
            import _pyhk
            return _pyhk
        try:
            _mod = imp.load_module('_pyhk', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _pyhk = swig_import_helper()
    del swig_import_helper
else:
    import _pyhk
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

TRUE = _pyhk.TRUE
FALSE = _pyhk.FALSE
NULL = _pyhk.NULL
class INITINFO(_object):
    """Proxy of C++ tagInitInfo class."""

    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, INITINFO, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, INITINFO, name)
    __repr__ = _swig_repr
    __swig_setmethods__["uWidth"] = _pyhk.INITINFO_uWidth_set
    __swig_getmethods__["uWidth"] = _pyhk.INITINFO_uWidth_get
    if _newclass:
        uWidth = _swig_property(_pyhk.INITINFO_uWidth_get, _pyhk.INITINFO_uWidth_set)
    __swig_setmethods__["uHeight"] = _pyhk.INITINFO_uHeight_set
    __swig_getmethods__["uHeight"] = _pyhk.INITINFO_uHeight_get
    if _newclass:
        uHeight = _swig_property(_pyhk.INITINFO_uHeight_get, _pyhk.INITINFO_uHeight_set)

    def __init__(self):
        """__init__(self) -> INITINFO"""
        this = _pyhk.new_INITINFO()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _pyhk.delete_INITINFO
    __del__ = lambda self: None
INITINFO_swigregister = _pyhk.INITINFO_swigregister
INITINFO_swigregister(INITINFO)

class NET_DVR_TIME(_object):
    """Proxy of C++ NET_DVR_TIME class."""

    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, NET_DVR_TIME, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, NET_DVR_TIME, name)
    __repr__ = _swig_repr
    __swig_setmethods__["dwYear"] = _pyhk.NET_DVR_TIME_dwYear_set
    __swig_getmethods__["dwYear"] = _pyhk.NET_DVR_TIME_dwYear_get
    if _newclass:
        dwYear = _swig_property(_pyhk.NET_DVR_TIME_dwYear_get, _pyhk.NET_DVR_TIME_dwYear_set)
    __swig_setmethods__["dwMonth"] = _pyhk.NET_DVR_TIME_dwMonth_set
    __swig_getmethods__["dwMonth"] = _pyhk.NET_DVR_TIME_dwMonth_get
    if _newclass:
        dwMonth = _swig_property(_pyhk.NET_DVR_TIME_dwMonth_get, _pyhk.NET_DVR_TIME_dwMonth_set)
    __swig_setmethods__["dwDay"] = _pyhk.NET_DVR_TIME_dwDay_set
    __swig_getmethods__["dwDay"] = _pyhk.NET_DVR_TIME_dwDay_get
    if _newclass:
        dwDay = _swig_property(_pyhk.NET_DVR_TIME_dwDay_get, _pyhk.NET_DVR_TIME_dwDay_set)
    __swig_setmethods__["dwHour"] = _pyhk.NET_DVR_TIME_dwHour_set
    __swig_getmethods__["dwHour"] = _pyhk.NET_DVR_TIME_dwHour_get
    if _newclass:
        dwHour = _swig_property(_pyhk.NET_DVR_TIME_dwHour_get, _pyhk.NET_DVR_TIME_dwHour_set)
    __swig_setmethods__["dwMinute"] = _pyhk.NET_DVR_TIME_dwMinute_set
    __swig_getmethods__["dwMinute"] = _pyhk.NET_DVR_TIME_dwMinute_get
    if _newclass:
        dwMinute = _swig_property(_pyhk.NET_DVR_TIME_dwMinute_get, _pyhk.NET_DVR_TIME_dwMinute_set)
    __swig_setmethods__["dwSecond"] = _pyhk.NET_DVR_TIME_dwSecond_set
    __swig_getmethods__["dwSecond"] = _pyhk.NET_DVR_TIME_dwSecond_get
    if _newclass:
        dwSecond = _swig_property(_pyhk.NET_DVR_TIME_dwSecond_get, _pyhk.NET_DVR_TIME_dwSecond_set)

    def __init__(self):
        """__init__(self) -> NET_DVR_TIME"""
        this = _pyhk.new_NET_DVR_TIME()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _pyhk.delete_NET_DVR_TIME
    __del__ = lambda self: None
NET_DVR_TIME_swigregister = _pyhk.NET_DVR_TIME_swigregister
NET_DVR_TIME_swigregister(NET_DVR_TIME)

class NET_DVR_DEVICEINFO_V30(_object):
    """Proxy of C++ NET_DVR_DEVICEINFO_V30 class."""

    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, NET_DVR_DEVICEINFO_V30, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, NET_DVR_DEVICEINFO_V30, name)
    __repr__ = _swig_repr
    __swig_setmethods__["sSerialNumber"] = _pyhk.NET_DVR_DEVICEINFO_V30_sSerialNumber_set
    __swig_getmethods__["sSerialNumber"] = _pyhk.NET_DVR_DEVICEINFO_V30_sSerialNumber_get
    if _newclass:
        sSerialNumber = _swig_property(_pyhk.NET_DVR_DEVICEINFO_V30_sSerialNumber_get, _pyhk.NET_DVR_DEVICEINFO_V30_sSerialNumber_set)
    __swig_setmethods__["byAlarmInPortNum"] = _pyhk.NET_DVR_DEVICEINFO_V30_byAlarmInPortNum_set
    __swig_getmethods__["byAlarmInPortNum"] = _pyhk.NET_DVR_DEVICEINFO_V30_byAlarmInPortNum_get
    if _newclass:
        byAlarmInPortNum = _swig_property(_pyhk.NET_DVR_DEVICEINFO_V30_byAlarmInPortNum_get, _pyhk.NET_DVR_DEVICEINFO_V30_byAlarmInPortNum_set)
    __swig_setmethods__["byAlarmOutPortNum"] = _pyhk.NET_DVR_DEVICEINFO_V30_byAlarmOutPortNum_set
    __swig_getmethods__["byAlarmOutPortNum"] = _pyhk.NET_DVR_DEVICEINFO_V30_byAlarmOutPortNum_get
    if _newclass:
        byAlarmOutPortNum = _swig_property(_pyhk.NET_DVR_DEVICEINFO_V30_byAlarmOutPortNum_get, _pyhk.NET_DVR_DEVICEINFO_V30_byAlarmOutPortNum_set)
    __swig_setmethods__["byDiskNum"] = _pyhk.NET_DVR_DEVICEINFO_V30_byDiskNum_set
    __swig_getmethods__["byDiskNum"] = _pyhk.NET_DVR_DEVICEINFO_V30_byDiskNum_get
    if _newclass:
        byDiskNum = _swig_property(_pyhk.NET_DVR_DEVICEINFO_V30_byDiskNum_get, _pyhk.NET_DVR_DEVICEINFO_V30_byDiskNum_set)
    __swig_setmethods__["byDVRType"] = _pyhk.NET_DVR_DEVICEINFO_V30_byDVRType_set
    __swig_getmethods__["byDVRType"] = _pyhk.NET_DVR_DEVICEINFO_V30_byDVRType_get
    if _newclass:
        byDVRType = _swig_property(_pyhk.NET_DVR_DEVICEINFO_V30_byDVRType_get, _pyhk.NET_DVR_DEVICEINFO_V30_byDVRType_set)
    __swig_setmethods__["byChanNum"] = _pyhk.NET_DVR_DEVICEINFO_V30_byChanNum_set
    __swig_getmethods__["byChanNum"] = _pyhk.NET_DVR_DEVICEINFO_V30_byChanNum_get
    if _newclass:
        byChanNum = _swig_property(_pyhk.NET_DVR_DEVICEINFO_V30_byChanNum_get, _pyhk.NET_DVR_DEVICEINFO_V30_byChanNum_set)
    __swig_setmethods__["byStartChan"] = _pyhk.NET_DVR_DEVICEINFO_V30_byStartChan_set
    __swig_getmethods__["byStartChan"] = _pyhk.NET_DVR_DEVICEINFO_V30_byStartChan_get
    if _newclass:
        byStartChan = _swig_property(_pyhk.NET_DVR_DEVICEINFO_V30_byStartChan_get, _pyhk.NET_DVR_DEVICEINFO_V30_byStartChan_set)
    __swig_setmethods__["byAudioChanNum"] = _pyhk.NET_DVR_DEVICEINFO_V30_byAudioChanNum_set
    __swig_getmethods__["byAudioChanNum"] = _pyhk.NET_DVR_DEVICEINFO_V30_byAudioChanNum_get
    if _newclass:
        byAudioChanNum = _swig_property(_pyhk.NET_DVR_DEVICEINFO_V30_byAudioChanNum_get, _pyhk.NET_DVR_DEVICEINFO_V30_byAudioChanNum_set)
    __swig_setmethods__["byIPChanNum"] = _pyhk.NET_DVR_DEVICEINFO_V30_byIPChanNum_set
    __swig_getmethods__["byIPChanNum"] = _pyhk.NET_DVR_DEVICEINFO_V30_byIPChanNum_get
    if _newclass:
        byIPChanNum = _swig_property(_pyhk.NET_DVR_DEVICEINFO_V30_byIPChanNum_get, _pyhk.NET_DVR_DEVICEINFO_V30_byIPChanNum_set)
    __swig_setmethods__["byZeroChanNum"] = _pyhk.NET_DVR_DEVICEINFO_V30_byZeroChanNum_set
    __swig_getmethods__["byZeroChanNum"] = _pyhk.NET_DVR_DEVICEINFO_V30_byZeroChanNum_get
    if _newclass:
        byZeroChanNum = _swig_property(_pyhk.NET_DVR_DEVICEINFO_V30_byZeroChanNum_get, _pyhk.NET_DVR_DEVICEINFO_V30_byZeroChanNum_set)
    __swig_setmethods__["byMainProto"] = _pyhk.NET_DVR_DEVICEINFO_V30_byMainProto_set
    __swig_getmethods__["byMainProto"] = _pyhk.NET_DVR_DEVICEINFO_V30_byMainProto_get
    if _newclass:
        byMainProto = _swig_property(_pyhk.NET_DVR_DEVICEINFO_V30_byMainProto_get, _pyhk.NET_DVR_DEVICEINFO_V30_byMainProto_set)
    __swig_setmethods__["bySubProto"] = _pyhk.NET_DVR_DEVICEINFO_V30_bySubProto_set
    __swig_getmethods__["bySubProto"] = _pyhk.NET_DVR_DEVICEINFO_V30_bySubProto_get
    if _newclass:
        bySubProto = _swig_property(_pyhk.NET_DVR_DEVICEINFO_V30_bySubProto_get, _pyhk.NET_DVR_DEVICEINFO_V30_bySubProto_set)
    __swig_setmethods__["bySupport"] = _pyhk.NET_DVR_DEVICEINFO_V30_bySupport_set
    __swig_getmethods__["bySupport"] = _pyhk.NET_DVR_DEVICEINFO_V30_bySupport_get
    if _newclass:
        bySupport = _swig_property(_pyhk.NET_DVR_DEVICEINFO_V30_bySupport_get, _pyhk.NET_DVR_DEVICEINFO_V30_bySupport_set)
    __swig_setmethods__["bySupport1"] = _pyhk.NET_DVR_DEVICEINFO_V30_bySupport1_set
    __swig_getmethods__["bySupport1"] = _pyhk.NET_DVR_DEVICEINFO_V30_bySupport1_get
    if _newclass:
        bySupport1 = _swig_property(_pyhk.NET_DVR_DEVICEINFO_V30_bySupport1_get, _pyhk.NET_DVR_DEVICEINFO_V30_bySupport1_set)
    __swig_setmethods__["bySupport2"] = _pyhk.NET_DVR_DEVICEINFO_V30_bySupport2_set
    __swig_getmethods__["bySupport2"] = _pyhk.NET_DVR_DEVICEINFO_V30_bySupport2_get
    if _newclass:
        bySupport2 = _swig_property(_pyhk.NET_DVR_DEVICEINFO_V30_bySupport2_get, _pyhk.NET_DVR_DEVICEINFO_V30_bySupport2_set)
    __swig_setmethods__["wDevType"] = _pyhk.NET_DVR_DEVICEINFO_V30_wDevType_set
    __swig_getmethods__["wDevType"] = _pyhk.NET_DVR_DEVICEINFO_V30_wDevType_get
    if _newclass:
        wDevType = _swig_property(_pyhk.NET_DVR_DEVICEINFO_V30_wDevType_get, _pyhk.NET_DVR_DEVICEINFO_V30_wDevType_set)
    __swig_setmethods__["bySupport3"] = _pyhk.NET_DVR_DEVICEINFO_V30_bySupport3_set
    __swig_getmethods__["bySupport3"] = _pyhk.NET_DVR_DEVICEINFO_V30_bySupport3_get
    if _newclass:
        bySupport3 = _swig_property(_pyhk.NET_DVR_DEVICEINFO_V30_bySupport3_get, _pyhk.NET_DVR_DEVICEINFO_V30_bySupport3_set)
    __swig_setmethods__["byMultiStreamProto"] = _pyhk.NET_DVR_DEVICEINFO_V30_byMultiStreamProto_set
    __swig_getmethods__["byMultiStreamProto"] = _pyhk.NET_DVR_DEVICEINFO_V30_byMultiStreamProto_get
    if _newclass:
        byMultiStreamProto = _swig_property(_pyhk.NET_DVR_DEVICEINFO_V30_byMultiStreamProto_get, _pyhk.NET_DVR_DEVICEINFO_V30_byMultiStreamProto_set)
    __swig_setmethods__["byStartDChan"] = _pyhk.NET_DVR_DEVICEINFO_V30_byStartDChan_set
    __swig_getmethods__["byStartDChan"] = _pyhk.NET_DVR_DEVICEINFO_V30_byStartDChan_get
    if _newclass:
        byStartDChan = _swig_property(_pyhk.NET_DVR_DEVICEINFO_V30_byStartDChan_get, _pyhk.NET_DVR_DEVICEINFO_V30_byStartDChan_set)
    __swig_setmethods__["byStartDTalkChan"] = _pyhk.NET_DVR_DEVICEINFO_V30_byStartDTalkChan_set
    __swig_getmethods__["byStartDTalkChan"] = _pyhk.NET_DVR_DEVICEINFO_V30_byStartDTalkChan_get
    if _newclass:
        byStartDTalkChan = _swig_property(_pyhk.NET_DVR_DEVICEINFO_V30_byStartDTalkChan_get, _pyhk.NET_DVR_DEVICEINFO_V30_byStartDTalkChan_set)
    __swig_setmethods__["byHighDChanNum"] = _pyhk.NET_DVR_DEVICEINFO_V30_byHighDChanNum_set
    __swig_getmethods__["byHighDChanNum"] = _pyhk.NET_DVR_DEVICEINFO_V30_byHighDChanNum_get
    if _newclass:
        byHighDChanNum = _swig_property(_pyhk.NET_DVR_DEVICEINFO_V30_byHighDChanNum_get, _pyhk.NET_DVR_DEVICEINFO_V30_byHighDChanNum_set)
    __swig_setmethods__["bySupport4"] = _pyhk.NET_DVR_DEVICEINFO_V30_bySupport4_set
    __swig_getmethods__["bySupport4"] = _pyhk.NET_DVR_DEVICEINFO_V30_bySupport4_get
    if _newclass:
        bySupport4 = _swig_property(_pyhk.NET_DVR_DEVICEINFO_V30_bySupport4_get, _pyhk.NET_DVR_DEVICEINFO_V30_bySupport4_set)
    __swig_setmethods__["byLanguageType"] = _pyhk.NET_DVR_DEVICEINFO_V30_byLanguageType_set
    __swig_getmethods__["byLanguageType"] = _pyhk.NET_DVR_DEVICEINFO_V30_byLanguageType_get
    if _newclass:
        byLanguageType = _swig_property(_pyhk.NET_DVR_DEVICEINFO_V30_byLanguageType_get, _pyhk.NET_DVR_DEVICEINFO_V30_byLanguageType_set)
    __swig_setmethods__["byVoiceInChanNum"] = _pyhk.NET_DVR_DEVICEINFO_V30_byVoiceInChanNum_set
    __swig_getmethods__["byVoiceInChanNum"] = _pyhk.NET_DVR_DEVICEINFO_V30_byVoiceInChanNum_get
    if _newclass:
        byVoiceInChanNum = _swig_property(_pyhk.NET_DVR_DEVICEINFO_V30_byVoiceInChanNum_get, _pyhk.NET_DVR_DEVICEINFO_V30_byVoiceInChanNum_set)
    __swig_setmethods__["byStartVoiceInChanNo"] = _pyhk.NET_DVR_DEVICEINFO_V30_byStartVoiceInChanNo_set
    __swig_getmethods__["byStartVoiceInChanNo"] = _pyhk.NET_DVR_DEVICEINFO_V30_byStartVoiceInChanNo_get
    if _newclass:
        byStartVoiceInChanNo = _swig_property(_pyhk.NET_DVR_DEVICEINFO_V30_byStartVoiceInChanNo_get, _pyhk.NET_DVR_DEVICEINFO_V30_byStartVoiceInChanNo_set)
    __swig_setmethods__["bySupport5"] = _pyhk.NET_DVR_DEVICEINFO_V30_bySupport5_set
    __swig_getmethods__["bySupport5"] = _pyhk.NET_DVR_DEVICEINFO_V30_bySupport5_get
    if _newclass:
        bySupport5 = _swig_property(_pyhk.NET_DVR_DEVICEINFO_V30_bySupport5_get, _pyhk.NET_DVR_DEVICEINFO_V30_bySupport5_set)
    __swig_setmethods__["bySupport6"] = _pyhk.NET_DVR_DEVICEINFO_V30_bySupport6_set
    __swig_getmethods__["bySupport6"] = _pyhk.NET_DVR_DEVICEINFO_V30_bySupport6_get
    if _newclass:
        bySupport6 = _swig_property(_pyhk.NET_DVR_DEVICEINFO_V30_bySupport6_get, _pyhk.NET_DVR_DEVICEINFO_V30_bySupport6_set)
    __swig_setmethods__["byMirrorChanNum"] = _pyhk.NET_DVR_DEVICEINFO_V30_byMirrorChanNum_set
    __swig_getmethods__["byMirrorChanNum"] = _pyhk.NET_DVR_DEVICEINFO_V30_byMirrorChanNum_get
    if _newclass:
        byMirrorChanNum = _swig_property(_pyhk.NET_DVR_DEVICEINFO_V30_byMirrorChanNum_get, _pyhk.NET_DVR_DEVICEINFO_V30_byMirrorChanNum_set)
    __swig_setmethods__["wStartMirrorChanNo"] = _pyhk.NET_DVR_DEVICEINFO_V30_wStartMirrorChanNo_set
    __swig_getmethods__["wStartMirrorChanNo"] = _pyhk.NET_DVR_DEVICEINFO_V30_wStartMirrorChanNo_get
    if _newclass:
        wStartMirrorChanNo = _swig_property(_pyhk.NET_DVR_DEVICEINFO_V30_wStartMirrorChanNo_get, _pyhk.NET_DVR_DEVICEINFO_V30_wStartMirrorChanNo_set)
    __swig_setmethods__["bySupport7"] = _pyhk.NET_DVR_DEVICEINFO_V30_bySupport7_set
    __swig_getmethods__["bySupport7"] = _pyhk.NET_DVR_DEVICEINFO_V30_bySupport7_get
    if _newclass:
        bySupport7 = _swig_property(_pyhk.NET_DVR_DEVICEINFO_V30_bySupport7_get, _pyhk.NET_DVR_DEVICEINFO_V30_bySupport7_set)
    __swig_setmethods__["byRes2"] = _pyhk.NET_DVR_DEVICEINFO_V30_byRes2_set
    __swig_getmethods__["byRes2"] = _pyhk.NET_DVR_DEVICEINFO_V30_byRes2_get
    if _newclass:
        byRes2 = _swig_property(_pyhk.NET_DVR_DEVICEINFO_V30_byRes2_get, _pyhk.NET_DVR_DEVICEINFO_V30_byRes2_set)

    def __init__(self):
        """__init__(self) -> NET_DVR_DEVICEINFO_V30"""
        this = _pyhk.new_NET_DVR_DEVICEINFO_V30()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _pyhk.delete_NET_DVR_DEVICEINFO_V30
    __del__ = lambda self: None
NET_DVR_DEVICEINFO_V30_swigregister = _pyhk.NET_DVR_DEVICEINFO_V30_swigregister
NET_DVR_DEVICEINFO_V30_swigregister(NET_DVR_DEVICEINFO_V30)

class CallbackStruct(_object):
    """Proxy of C++ CallbackStruct class."""

    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, CallbackStruct, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, CallbackStruct, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    def fExceptionCallBack(self, dwType: 'DWORD', lUserID: 'LONG', lHandle: 'LONG', pUser: 'void *') -> "void":
        """
        fExceptionCallBack(self, dwType, lUserID, lHandle, pUser)

        Parameters
        ----------
        dwType: DWORD
        lUserID: LONG
        lHandle: LONG
        pUser: void *

        """
        return _pyhk.CallbackStruct_fExceptionCallBack(self, dwType, lUserID, lHandle, pUser)

    __swig_destroy__ = _pyhk.delete_CallbackStruct
    __del__ = lambda self: None
CallbackStruct_swigregister = _pyhk.CallbackStruct_swigregister
CallbackStruct_swigregister(CallbackStruct)


def NET_DVR_SetExceptionCallBack_V30_wrapper(reserved1: 'UINT', reserved2: 'void *', cbExceptionCallBack: 'CallbackStruct', pUser: 'void *') -> "int":
    """
    NET_DVR_SetExceptionCallBack_V30_wrapper(reserved1, reserved2, cbExceptionCallBack, pUser) -> int

    Parameters
    ----------
    reserved1: UINT
    reserved2: void *
    cbExceptionCallBack: CallbackStruct *
    pUser: void *

    """
    return _pyhk.NET_DVR_SetExceptionCallBack_V30_wrapper(reserved1, reserved2, cbExceptionCallBack, pUser)

def NET_DVR_Init() -> "BOOL":
    """NET_DVR_Init() -> BOOL"""
    return _pyhk.NET_DVR_Init()

def NET_DVR_SetConnectTime(dwWaitTime: 'DWORD', dwTryTimes: 'DWORD') -> "BOOL":
    """
    NET_DVR_SetConnectTime(dwWaitTime, dwTryTimes) -> BOOL

    Parameters
    ----------
    dwWaitTime: DWORD
    dwTryTimes: DWORD

    """
    return _pyhk.NET_DVR_SetConnectTime(dwWaitTime, dwTryTimes)

def NET_DVR_GetLastError() -> "DWORD":
    """NET_DVR_GetLastError() -> DWORD"""
    return _pyhk.NET_DVR_GetLastError()

def NET_DVR_Login_V30(sDVRIP: 'char *', wDVRPort: 'WORD', sUserName: 'char *', sPassword: 'char *', lpDeviceInfo: 'NET_DVR_DEVICEINFO_V30') -> "LONG":
    """
    NET_DVR_Login_V30(sDVRIP, wDVRPort, sUserName, sPassword, lpDeviceInfo) -> LONG

    Parameters
    ----------
    sDVRIP: char *
    wDVRPort: WORD
    sUserName: char *
    sPassword: char *
    lpDeviceInfo: LPNET_DVR_DEVICEINFO_V30

    """
    return _pyhk.NET_DVR_Login_V30(sDVRIP, wDVRPort, sUserName, sPassword, lpDeviceInfo)

def NET_DVR_GetDVRConfig(lUserID: 'LONG', dwCommand: 'DWORD', lChannel: 'LONG', lpOutBuffer: 'LPVOID', dwOutBufferSize: 'DWORD', lpBytesReturned: 'LPDWORD') -> "BOOL":
    """
    NET_DVR_GetDVRConfig(lUserID, dwCommand, lChannel, lpOutBuffer, dwOutBufferSize, lpBytesReturned) -> BOOL

    Parameters
    ----------
    lUserID: LONG
    dwCommand: DWORD
    lChannel: LONG
    lpOutBuffer: LPVOID
    dwOutBufferSize: DWORD
    lpBytesReturned: LPDWORD

    """
    return _pyhk.NET_DVR_GetDVRConfig(lUserID, dwCommand, lChannel, lpOutBuffer, dwOutBufferSize, lpBytesReturned)

def NET_DVR_SetDVRConfig(lUserID: 'LONG', dwCommand: 'DWORD', lChannel: 'LONG', lpInBuffer: 'LPVOID', dwInBufferSize: 'DWORD') -> "BOOL":
    """
    NET_DVR_SetDVRConfig(lUserID, dwCommand, lChannel, lpInBuffer, dwInBufferSize) -> BOOL

    Parameters
    ----------
    lUserID: LONG
    dwCommand: DWORD
    lChannel: LONG
    lpInBuffer: LPVOID
    dwInBufferSize: DWORD

    """
    return _pyhk.NET_DVR_SetDVRConfig(lUserID, dwCommand, lChannel, lpInBuffer, dwInBufferSize)

def test(x: 'NET_DVR_TIME') -> "void":
    """
    test(x)

    Parameters
    ----------
    x: LPNET_DVR_TIME

    """
    return _pyhk.test(x)
# This file is compatible with both classic and new-style classes.


